### ISSUE TITLE
闭包实现选项卡切换

### ISSUE THREAD

**Issue by jeffsui** [jeffsui/jeffsui.github.io#134]
## 准备好html和css
```css
.wrapper {
				box-shadow: -2px 0 5px lightsteelblue, 0 -2px 5px lightsteelblue, 0 2px 5px lightsteelblue, 2px 0 5px lightsteelblue;
				height: 450px;
				width: 533px;
			}
			
			.content {
				display: none;
				width: 530px;
				height: 395px;
				margin-top: 8px;
				box-shadow: -2px 0 5px gray, 0 -2px 5px gray, 0 2px 5px gray, 2px 0 5px gray;
			}
			/*点击该按钮的时候显示该颜色*/
			
			.active {
				background-color: lightsteelblue;
			}
			
			button {
				background-color: lightseagreen;
				margin-top: 5px;
				list-style-type: none;
				width: 125px;
				height: 40px;
				font-family: "新宋体";
				font-size: 18px;
				border: none;
				box-shadow: -2px 0 5px lightsteelblue, 0 -2px 5px lightsteelblue, 0 2px 5px lightsteelblue, 2px 0 5px lightsteelblue;
			}
			
			button:first-child {
				margin-left: 10px;
			}
```

```html
.wrapper>button.active+button*3{选项卡$}+.content*3>img
```
## javascript部分
```javascript
 var btn = document.querySelectorAll("button");
        var div = document.querySelectorAll('.content');
        for (var n = 0; n < btn.length; n++) {
            (function (i) {
                btn[n].onclick = function () {
                    for (var j = 0; j < btn.length; j++) {
                        btn[j].className = "";
                        div[j].style.display = 'none';
                    }
                    this.className = 'active';
                    div[i].style.display = "block";
                }
            })(n);
        }
```
